use_frameworks!
source 'https://gitee.com/mirrors/CocoaPods-Specs'
platform :ios, '8.0'

target 'SilentKit_Example' do
  pod 'SilentKit', :path => '../'
  pod 'MJRefresh'
  pod 'AFNetworking'
  target 'SilentKit_Tests' do
    inherit! :search_paths

    
  end
end
